package ews.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ews.client.EngineWebService", targetNamespace = "urn:hpexstream-services/Engine")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EngineWebService {


    /**
     * 
     * @param ewsComposeRequest
     * @return
     *     returns wsproxy.ews.client.EwsComposeResponse
     * @throws EngineServiceException_Exception
     */
    @WebMethod(operationName = "ews.client.Compose")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ews.client.Compose", targetNamespace = "urn:hpexstream-services/Engine", className = "wsproxy.ews.client.Compose")
    @ResponseWrapper(localName = "ews.client.ComposeResponse", targetNamespace = "urn:hpexstream-services/Engine", className = "wsproxy.ews.client.ComposeResponse")
    @Action(input = "urn:hpexstream-services/Engine:ews.client.EngineWebService:ComposeRequest", output = "urn:hpexstream-services/Engine:ews.client.EngineWebService:ews.client.ComposeResponse", fault = {
        @FaultAction(className = EngineServiceException_Exception.class, value = "urn:hpexstream-services/Engine:ews.client.EngineWebService:ews.client.Compose:Fault:ews.client.EngineServiceException")
    })
    public EwsComposeResponse compose(
        @WebParam(name = "EWSComposeRequest", targetNamespace = "")
        EwsComposeRequest ewsComposeRequest)
        throws EngineServiceException_Exception
    ;

}
