
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EngineWebService", targetNamespace = "urn:hpexstream-services/Engine")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EngineWebService {


    /**
     * 
     * @param ewsComposeRequest
     * @return
     *     returns wsproxy.EwsComposeResponse
     * @throws EngineServiceException_Exception
     */
    @WebMethod(operationName = "Compose")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Compose", targetNamespace = "urn:hpexstream-services/Engine", className = "wsproxy.Compose")
    @ResponseWrapper(localName = "ComposeResponse", targetNamespace = "urn:hpexstream-services/Engine", className = "wsproxy.ComposeResponse")
    @Action(input = "urn:hpexstream-services/Engine:EngineWebService:ComposeRequest", output = "urn:hpexstream-services/Engine:EngineWebService:ComposeResponse", fault = {
        @FaultAction(className = EngineServiceException_Exception.class, value = "urn:hpexstream-services/Engine:EngineWebService:Compose:Fault:EngineServiceException")
    })
    public EwsComposeResponse compose(
        @WebParam(name = "EWSComposeRequest", targetNamespace = "")
        EwsComposeRequest ewsComposeRequest)
        throws EngineServiceException_Exception
    ;

}
