import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "EngineServiceException", targetNamespace = "urn:hpexstream-services/Engine")
public class EngineServiceException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private EngineServiceException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public EngineServiceException_Exception(String message, EngineServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public EngineServiceException_Exception(String message, EngineServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: wsproxy.EngineServiceException
     */
    public EngineServiceException getFaultInfo() {
        return faultInfo;
    }

}
